name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:

      fail-fast: false
      matrix:
        php: [8.4, 8.3, 8.2, 8.1, 8.0]
        laravel: ["^11.0", "^10.0" , "^9.0"]
        dependency-version: [prefer-stable]
        include:
          - laravel: "^11.0"
            testbench: 9.*
            pest: ^3.0
          - laravel: "^10.0"
            testbench: 8.*
            pest: ^3.0
          - laravel: "^9.0"
            testbench: 7.*
            pest: ^3.0
        exclude:
          - laravel: "^11.0"
            php: 8.1
          - laravel: "^11.0"
            php: 8.0
          - laravel: "^10.0"
            php: 8.4
          - laravel: "^10.0"
            php: 8.0
          - laravel: "^9.0"
            php: 8.4
          - laravel: "^9.0"
            php: 8.3

    name: PHP${{ matrix.php }} | Laravel${{ matrix.laravel }} | ${{ matrix.dependency-version }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: fast_api_crud
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, zip, pdo, pdo_mysql, pcntl, bcmath, gd, soap, xsl, xml, xmlrpc, mbstring, curl, json, dom, iconv, simplexml, xmlwriter, xmlreader, phar, posix, ctype, tokenizer, session, fileinfo, filter, hash, openssl, pcre, SPL, Reflection, calendar, exif, gettext, sockets, standard, date, libxml, zlib
          coverage: none
          
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            ~/.cache/composer/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
  
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
          composer show

      - name: Run php pest tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: fast_api_crud
          DB_USERNAME: root
          DB_PASSWORD: admin
